### ISSUE TITLE
Crash when sending transaction with WalletConnect (Android)

### ISSUE THREAD

**Issue by ligi** [rainbow-me/rainbow#1601]
stacktrace:

```
01-17 12:04:11.274 15100 15748 E AndroidRuntime: FATAL EXCEPTION: mqt_native_modules
01-17 12:04:11.274 15100 15748 E AndroidRuntime: Process: me.rainbow, PID: 15100
01-17 12:04:11.274 15100 15748 E AndroidRuntime: com.facebook.react.common.JavascriptException: TypeError: Cannot read property 'price' of undefined
01-17 12:04:11.274 15100 15748 E AndroidRuntime: 
01-17 12:04:11.274 15100 15748 E AndroidRuntime: This error is located at:
01-17 12:04:11.274 15100 15748 E AndroidRuntime:     in W
01-17 12:04:11.274 15100 15748 E AndroidRuntime:     in Unknown
01-17 12:04:11.274 15100 15748 E AndroidRuntime:     in Unknown
01-17 12:04:11.274 15100 15748 E AndroidRuntime:     in Unknown
01-17 12:04:11.274 15100 15748 E AndroidRuntime:     in Unknown
01-17 12:04:11.274 15100 15748 E AndroidRuntime:     in RCTView
01-17 12:04:11.274 15100 15748 E AndroidRuntime:     in View
01-17 12:04:11.274 15100 15748 E AndroidRuntime:     in RCTView
01-17 12:04:11.274 15100 15748 E AndroidRuntime:     in View
01-17 12:04:11.274 15100 15748 E AndroidRuntime:     in RCTView
01-17 12:04:11.274 15100 15748 E AndroidRuntime:     in View
01-17 12:04:11.274 15100 15748 E AndroidRuntime:     in ForwardRef
01-17 12:04:11.274 15100 15748 E AndroidRuntime:     in RCTView
01-17 12:04:11.274 15100 15748 E AndroidRuntime:     in View
01-17 12:04:11.274 15100 15748 E AndroidRuntime:     in p
01-17 12:04:11.274 15100 15748 E AndroidRuntime:     in ForwardRef
01-17 12:04:11.274 15100 15748 E AndroidRuntime:     in PanGestureHandler
01-17 12:04:11.274 15100 15748 E AndroidRuntime:     in Unknown
01-17 12:04:11.274 15100 15748 E AndroidRuntime:     in RCTView
01-17 12:04:11.274 15100 15748 E AndroidRuntime:     in View
01-17 12:04:11.274 15100 15748 E AndroidRuntime:     in p
01-17 12:04:11.274 15100 15748 E AndroidRuntime:     in ForwardRef
01-17 12:04:11.274 15100 15748 E AndroidRuntime:     in RCTView
01-17 12:04:11.274 15100 15748 E AndroidRuntime:     in View
01-17 12:04:11.274 15100 15748 E AndroidRuntime:     in G
01-17 12:04:11.274 15100 15748 E AndroidRuntime:     in Unknown
01-17 12:04:11.274 15100 15748 E AndroidRuntime:     in RCTView
01-17 12:04:11.274 15100 15748 E AndroidRuntime:     in View
01-17 12:04:11.274 15100 15748 E AndroidRuntime:     in Unknown
01-17 12:04:11.274 15100 15748 E AndroidRuntime:     in RCTView
01-17 12:04:11.274 15100 15748 E AndroidRuntime:     in View
01-17 12:04:11.274 15100 15748 E AndroidRuntime:     in Unknown
01-17 12:04:11.274 15100 15748 E AndroidRuntime:     in C
01-17 12:04:11.274 15100 15748 E AndroidRuntime:     in y
01-17 12:04:11.274 15100 15748 E AndroidRuntime:     in Unknown
01-17 12:04:11.274 15100 15748 E AndroidRuntime:     in RCTView
01-17 12:04:11.274 15100 15748 E AndroidRuntime:     in View
01-17 12:04:11.274 15100 15748 E AndroidRuntime:     in Unknown
01-17 12:04:11.274 15100 15748 E AndroidRuntime:     in j
01-17 12:04:11.274 15100 15748 E AndroidRuntime:     in Unknown
01-17 12:04:11.274 15100 15748 E AndroidRuntime:     in w
01-17 12:04:11.274 15100 15748 E AndroidRuntime:     in Unknown
01-17 12:04:11.274 15100 15748 E AndroidRuntime:     in Unknown
01-17 12:04:11.274 15100 15748 E AndroidRuntime:     in Unknown
01-17 12:04:11.274 15100 15748 E AndroidRuntime:     in Unknown
01-17 12:04:11.274 15100 15748 E AndroidRuntime:     in RCTView
01-17 12:04:11.274 15100 15748 E AndroidRuntime:     in View
01-17 12:04:11.274 15100 15748 E AndroidRuntime:     in RCTView
01-17 12:04:11.274 15100 15748 E AndroidRuntime:     in View
01-17 12:04:11.274 15100 15748 E AndroidRuntime:     in RCTView
01-17 12:04:11.274 15100 15748 E AndroidRuntime:     in View
01-17 12:04:11.274 15100 15748 E AndroidRuntime:     in ForwardRef
01-17 12:04:11.274 15100 15748 E AndroidRuntime:     in RCTView
01-17 12:04:11.274 15100 15748 E AndroidRuntime:     in View
01-17 12:04:11.274 15100 15748 E AndroidRuntime:     in p
01-17 12:04:11.274 15100 15748 E AndroidRuntime:     in ForwardRef
01-17 12:04:11.274 15100 15748 E AndroidRuntime:     in PanGestureHandler
01-17 12:04:11.274 15100 15748 E AndroidRuntime:     in Unknown
01-17 12:04:11.274 15100 15748 E AndroidRuntime:     in RCTView
01-17 12:04:11.274 15100 15748 E AndroidRuntime:     in View
01-17 12:04:11.274 15100 15748 E AndroidRuntime:     in p
01-17 12:04:11.274 15100 15748 E AndroidRuntime:     in ForwardRef
01-17 12:04:11.274 15100 15748 E AndroidRuntime:     in RCTView
01-17 12:04:11.274 15100 15748 E AndroidRuntime:     in View
01-17 12:04:11.274 15100 15748 E AndroidRuntime:     in G
01-17 12:04:11.274 15100 15748 E AndroidRuntime:     in Unknown
01-17 12:04:11.274 15100 15748 E AndroidRuntime:     in RCTView
01-17 12:04:11.274 15100 15748 E AndroidRuntime:     in View
01-17 12:04:11.274 15100 15748 E AndroidRuntime:     in Unknown
01-17 12:04:11.274 15100 15748 E AndroidRuntime:     in RCTView
01-17 12:04:11.274 15100 15748 E AndroidRuntime:     in View
01-17 12:04:11.274 15100 15748 E AndroidRuntime:     in Unknown
01-17 12:04:11.274 15100 15748 E AndroidRuntime:     in C
01-17 12:04:11.274 15100 15748 E AndroidRuntime:     in y
01-17 12:04:11.274 15100 15748 E AndroidRuntime:     in Unknown
01-17 12:04:11.274 15100 15748 E AndroidRuntime:     in GestureHandlerRootView
01-17 12:04:11.274 15100 15748 E AndroidRuntime:     in Unknown
01-17 12:04:11.274 15100 15748 E AndroidRuntime:     in j
01-17 12:04:11.274 15100 15748 E AndroidRuntime:     in Unknown
01-17 12:04:11.274 15100 15748 E AndroidRuntime:     in k
01-17 12:04:11.274 15100 15748 E AndroidRuntime:     in Unknown
01-17 12:04:11.274 15100 15748 E AndroidRuntime:     in ForwardRef
01-17 12:04:11.274 15100 15748 E AndroidRuntime:     in Unknown
01-17 12:04:11.274 15100 15748 E AndroidRuntime:     in ForwardRef
01-17 12:04:11.274 15100 15748 E AndroidRuntime:     in AppContainerWithAnalytics
01-17 12:04:11.274 15100 15748 E AndroidRuntime:     in AppContainerWithAnalytics
01-17 12:04:11.274 15100 15748 E AndroidRuntime:     in RCTView
01-17 12:04:11.274 15100 15748 E AndroidRuntime:     in View
01-17 12:04:11.274 15100 15748 E AndroidRuntime:     in r
01-17 12:04:11.274 15100 15748 E AndroidRuntime:     in FlexItem
01-17 12:04:11.274 15100 15748 E AndroidRuntime:     in u
01-17 12:04:11.274 15100 15748 E AndroidRuntime:     in RNCSafeAreaView
01-17 12:04:11.274 15100 15748 E AndroidRuntime:     in Unknown
01-17 12:04:11.274 15100 15748 E AndroidRuntime:     in RCTView
01-17 12:04:11.274 15100 15748 E AndroidRuntime:     in View
01-17 12:04:11.274 15100 15748 E AndroidRuntime:     in Unknown
01-17 12:04:11.274 15100 15748 E AndroidRuntime:     in Unknown
01-17 12:04:11.274 15100 15748 E AndroidRuntime:     in w
01-17 12:04:11.274 15100 15748 E AndroidRuntime:     in A
01-17 12:04:11.274 15100 15748 E AndroidRuntime:     in A
01-17 12:04:11.274 15100 15748 E AndroidRuntime:     in s
01-17 12:04:11.274 15100 15748 E AndroidRuntime:     in A
01-17 12:04:11.274 15100 15748 E AndroidRuntime:     in Unknown
01-17 12:04:11.274 15100 15748 E AndroidRuntime:     in P
01-17 12:04:11.274 15100 15748 E AndroidRuntime:     in RCTView
01-17 12:04:11.274 15100 15748 E AndroidRuntime:     in View
01-17 12:04:11.274 15100 15748 E AndroidRuntime:     in RCTView
01-17 12:04:11.274 15100 15748 E AndroidRuntime:     in View
01-17 12:04:11.274 15100 15748 E AndroidRuntime:     in p, js engine: hermes, stack:
01-17 12:04:11.274 15100 15748 E AndroidRuntime: anonymous@1:5324398
01-17 12:04:11.274 15100 15748 E AndroidRuntime: W@1:5317291
01-17 12:04:11.274 15100 15748 E AndroidRuntime: Xn@1:221691
01-17 12:04:11.274 15100 15748 E AndroidRuntime: di@1:258194
01-17 12:04:11.274 15100 15748 E AndroidRuntime: dl@1:243593
01-17 12:04:11.274 15100 15748 E AndroidRuntime: cl@1:243450
01-17 12:04:11.274 15100 15748 E AndroidRuntime: sl@1:243340
01-17 12:04:11.274 15100 15748 E AndroidRuntime: rl@1:241131
01-17 12:04:11.274 15100 15748 E AndroidRuntime: anonymous@1:212396
01-17 12:04:11.274 15100 15748 E AndroidRuntime: anonymous@1:306955
01-17 12:04:11.274 15100 15748 E AndroidRuntime: Lt@1:211869
01-17 12:04:11.274 15100 15748 E AndroidRuntime: Wt@1:212214
01-17 12:04:11.274 15100 15748 E AndroidRuntime: jt@1:212108
01-17 12:04:11.274 15100 15748 E AndroidRuntime: Ji@1:238440
01-17 12:04:11.274 15100 15748 E AndroidRuntime: mr@1:224475
01-17 12:04:11.274 15100 15748 E AndroidRuntime: anonymous@1:2664300
01-17 12:04:11.274 15100 15748 E AndroidRuntime: anonymous@1:2674618
01-17 12:04:11.274 15100 15748 E AndroidRuntime: anonymous@1:2678919
01-17 12:04:11.274 15100 15748 E AndroidRuntime: anonymous@1:2678747
01-17 12:04:11.274 15100 15748 E AndroidRuntime: t@1:2677657
01-17 12:04:11.274 15100 15748 E AndroidRuntime: anonymous@1:2659046
01-17 12:04:11.274 15100 15748 E AndroidRuntime: anonymous@1:2682944
01-17 12:04:11.274 15100 15748 E AndroidRuntime: anonymous@1:2682882
01-17 12:04:11.274 15100 15748 E AndroidRuntime: anonymous@1:2682882
01-17 12:04:11.274 15100 15748 E AndroidRuntime: X@1:2658987
01-17 12:04:11.274 15100 15748 E AndroidRuntime: handleAction@1:2714921
01-17 12:04:11.274 15100 15748 E AndroidRuntime: anonymous@1:3124720
01-17 12:04:11.274 15100 15748 E AndroidRuntime: anonymous@1:266357
01-17 12:04:11.274 15100 15748 E AndroidRuntime: k@1:265592
01-17 12:04:11.274 15100 15748 E AndroidRuntime: callTimers@1:267451
01-17 12:04:11.274 15100 15748 E AndroidRuntime: value@1:151999
01-17 12:04:11.274 15100 15748 E AndroidRuntime: anonymous@1:150501
01-17 12:04:11.274 15100 15748 E AndroidRuntime: value@1:151471
01-17 12:04:11.274 15100 15748 E AndroidRuntime: value@1:150459
01-17 12:04:11.274 15100 15748 E AndroidRuntime: 
01-17 12:04:11.274 15100 15748 E AndroidRuntime: 	at com.facebook.react.modules.core.ExceptionsManagerModule.reportException(ExceptionsManagerModule.java:83)
01-17 12:04:11.274 15100 15748 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
01-17 12:04:11.274 15100 15748 E AndroidRuntime: 	at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:372)
01-17 12:04:11.274 15100 15748 E AndroidRuntime: 	at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:151)
01-17 12:04:11.274 15100 15748 E AndroidRuntime: 	at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
01-17 12:04:11.274 15100 15748 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:883)
01-17 12:04:11.274 15100 15748 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:100)
01-17 12:04:11.274 15100 15748 E AndroidRuntime: 	at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:27)
01-17 12:04:11.274 15100 15748 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:241)
01-17 12:04:11.274 15100 15748 E AndroidRuntime: 	at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:226)
01-17 12:04:11.274 15100 15748 E AndroidRuntime: 	at java.lang.Thread.run(Thread.java:919)

```

**Comment by skylarbarrera** [comment]
Hey @ligi 

This looks to have been fixed on our end and will be release in our next update in the next day or 2! 

Thanks 🌈

**Comment by ligi** [comment]
did you roll out the version? I still see the crash in the latest version
