### ISSUE TITLE
TypeError: Object is not a function

### ISSUE THREAD

**Issue by ligi** [rainbow-me/rainbow#1651]
```
01-30 21:00:28.377  4704  4733 I WindowManager:   SURFACE show Surface(name=me.rainbow/me.rainbow.MainActivity)/@0x12b9710 on display:0: me.rainbow/me.rainbow.MainActivity
01-30 21:00:28.381  4704  4738 W system_server: Insufficient pre-allocated space to mmap vdex.
01-30 21:00:28.383  4704  4738 I ActivityTaskManager: Displayed me.rainbow/.MainActivity: +247ms
01-30 21:00:28.387  4110  4110 D MOTO_ERD9610_PowerHAL: POWER_HINT_INTERACTION 0
01-30 21:00:28.391 15479 15545 E unknown:ReactNative: CatalystInstanceImpl caught native exception
01-30 21:00:28.391 15479 15545 E unknown:ReactNative: com.facebook.react.common.JavascriptException: TypeError: Object is not a function
01-30 21:00:28.391 15479 15545 E unknown:ReactNative: 
01-30 21:00:28.391 15479 15545 E unknown:ReactNative: This error is located at:
01-30 21:00:28.391 15479 15545 E unknown:ReactNative:     in Unknown
01-30 21:00:28.391 15479 15545 E unknown:ReactNative:     in w
01-30 21:00:28.391 15479 15545 E unknown:ReactNative:     in A
01-30 21:00:28.391 15479 15545 E unknown:ReactNative:     in A
01-30 21:00:28.391 15479 15545 E unknown:ReactNative:     in s
01-30 21:00:28.391 15479 15545 E unknown:ReactNative:     in A
01-30 21:00:28.391 15479 15545 E unknown:ReactNative:     in Unknown
01-30 21:00:28.391 15479 15545 E unknown:ReactNative:     in P
01-30 21:00:28.391 15479 15545 E unknown:ReactNative:     in RCTView
01-30 21:00:28.391 15479 15545 E unknown:ReactNative:     in View
01-30 21:00:28.391 15479 15545 E unknown:ReactNative:     in RCTView
01-30 21:00:28.391 15479 15545 E unknown:ReactNative:     in View
01-30 21:00:28.391 15479 15545 E unknown:ReactNative:     in p, js engine: hermes, stack:
01-30 21:00:28.391 15479 15545 E unknown:ReactNative: anonymous@1:233827
01-30 21:00:28.391 15479 15545 E unknown:ReactNative: anonymous@1:306955
01-30 21:00:28.391 15479 15545 E unknown:ReactNative: Lt@1:211869
01-30 21:00:28.391 15479 15545 E unknown:ReactNative: ei@1:233783
01-30 21:00:28.391 15479 15545 E unknown:ReactNative: ai@1:235759
01-30 21:00:28.391 15479 15545 E unknown:ReactNative: gl@1:245028
01-30 21:00:28.391 15479 15545 E unknown:ReactNative: anonymous@1:306955
01-30 21:00:28.391 15479 15545 E unknown:ReactNative: Lt@1:211869
01-30 21:00:28.391 15479 15545 E unknown:ReactNative: ml@1:244296
01-30 21:00:28.391 15479 15545 E unknown:ReactNative: rl@1:241223
01-30 21:00:28.391 15479 15545 E unknown:ReactNative: anonymous@1:212396
01-30 21:00:28.391 15479 15545 E unknown:ReactNative: anonymous@1:306955
01-30 21:00:28.391 15479 15545 E unknown:ReactNative: Lt@1:211869
01-30 21:00:28.391 15479 15545 E unknown:ReactNative: Wt@1:212214
01-30 21:00:28.391 15479 15545 E unknown:ReactNative: jt@1:212108
01-30 21:00:28.391 15479 15545 E unknown:ReactNative: Ji@1:238440
01-30 21:00:28.391 15479 15545 E unknown:ReactNative: Ql@1:249568
01-30 21:00:28.391 15479 15545 E unknown:ReactNative: Bl@1:249874
01-30 21:00:28.391 15479 15545 E unknown:ReactNative: anonymous@1:259256
01-30 21:00:28.391 15479 15545 E unknown:ReactNative: unmountApplicationComponentAtRootTag@1:520609
01-30 21:00:28.391 15479 15545 E unknown:ReactNative: value@1:151999
01-30 21:00:28.391 15479 15545 E unknown:ReactNative: anonymous@1:150501
01-30 21:00:28.391 15479 15545 E unknown:ReactNative: value@1:151471
01-30 21:00:28.391 15479 15545 E unknown:ReactNative: value@1:150459
01-30 21:00:28.391 15479 15545 E unknown:ReactNative: 
01-30 21:00:28.391 15479 15545 E unknown:ReactNative: 	at com.facebook.react.modules.core.ExceptionsManagerModule.reportException(ExceptionsManagerModule.java:83)
01-30 21:00:28.391 15479 15545 E unknown:ReactNative: 	at java.lang.reflect.Method.invoke(Native Method)
01-30 21:00:28.391 15479 15545 E unknown:ReactNative: 	at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:372)
01-30 21:00:28.391 15479 15545 E unknown:ReactNative: 	at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:151)
01-30 21:00:28.391 15479 15545 E unknown:ReactNative: 	at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
01-30 21:00:28.391 15479 15545 E unknown:ReactNative: 	at android.os.Handler.handleCallback(Handler.java:883)
01-30 21:00:28.391 15479 15545 E unknown:ReactNative: 	at android.os.Handler.dispatchMessage(Handler.java:100)
01-30 21:00:28.391 15479 15545 E unknown:ReactNative: 	at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:27)
01-30 21:00:28.391 15479 15545 E unknown:ReactNative: 	at android.os.Looper.loop(Looper.java:241)
01-30 21:00:28.391 15479 15545 E unknown:ReactNative: 	at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:226)
01-30 21:00:28.391 15479 15545 E unknown:ReactNative: 	at java.lang.Thread.run(Thread.java:919)
01-30 21:00:28.391 15479 15545 E unknown:DisabledDevSupportManager: Caught exception
01-30 21:00:28.391 15479 15545 E unknown:DisabledDevSupportManager: com.facebook.react.common.JavascriptException: TypeError: Object is not a function
01-30 21:00:28.391 15479 15545 E unknown:DisabledDevSupportManager: 
01-30 21:00:28.391 15479 15545 E unknown:DisabledDevSupportManager: This error is located at:
01-30 21:00:28.391 15479 15545 E unknown:DisabledDevSupportManager:     in Unknown
01-30 21:00:28.391 15479 15545 E unknown:DisabledDevSupportManager:     in w
01-30 21:00:28.391 15479 15545 E unknown:DisabledDevSupportManager:     in A
01-30 21:00:28.391 15479 15545 E unknown:DisabledDevSupportManager:     in A
01-30 21:00:28.391 15479 15545 E unknown:DisabledDevSupportManager:     in s
01-30 21:00:28.391 15479 15545 E unknown:DisabledDevSupportManager:     in A
01-30 21:00:28.391 15479 15545 E unknown:DisabledDevSupportManager:     in Unknown
01-30 21:00:28.391 15479 15545 E unknown:DisabledDevSupportManager:     in P
01-30 21:00:28.391 15479 15545 E unknown:DisabledDevSupportManager:     in RCTView
01-30 21:00:28.391 15479 15545 E unknown:DisabledDevSupportManager:     in View
01-30 21:00:28.391 15479 15545 E unknown:DisabledDevSupportManager:     in RCTView
01-30 21:00:28.391 15479 15545 E unknown:DisabledDevSupportManager:     in View
01-30 21:00:28.391 15479 15545 E unknown:DisabledDevSupportManager:     in p, js engine: hermes, stack:
01-30 21:00:28.391 15479 15545 E unknown:DisabledDevSupportManager: anonymous@1:233827
01-30 21:00:28.391 15479 15545 E unknown:DisabledDevSupportManager: anonymous@1:306955
01-30 21:00:28.391 15479 15545 E unknown:DisabledDevSupportManager: Lt@1:211869
01-30 21:00:28.391 15479 15545 E unknown:DisabledDevSupportManager: ei@1:233783
01-30 21:00:28.391 15479 15545 E unknown:DisabledDevSupportManager: ai@1:235759
01-30 21:00:28.391 15479 15545 E unknown:DisabledDevSupportManager: gl@1:245028
01-30 21:00:28.391 15479 15545 E unknown:DisabledDevSupportManager: anonymous@1:306955
01-30 21:00:28.391 15479 15545 E unknown:DisabledDevSupportManager: Lt@1:211869
01-30 21:00:28.391 15479 15545 E unknown:DisabledDevSupportManager: ml@1:244296
01-30 21:00:28.391 15479 15545 E unknown:DisabledDevSupportManager: rl@1:241223
01-30 21:00:28.391 15479 15545 E unknown:DisabledDevSupportManager: anonymous@1:212396
01-30 21:00:28.391 15479 15545 E unknown:DisabledDevSupportManager: anonymous@1:306955
01-30 21:00:28.391 15479 15545 E unknown:DisabledDevSupportManager: Lt@1:211869
01-30 21:00:28.391 15479 15545 E unknown:DisabledDevSupportManager: Wt@1:212214
01-30 21:00:28.391 15479 15545 E unknown:DisabledDevSupportManager: jt@1:212108
01-30 21:00:28.391 15479 15545 E unknown:DisabledDevSupportManager: Ji@1:238440
01-30 21:00:28.391 15479 15545 E unknown:DisabledDevSupportManager: Ql@1:249568
01-30 21:00:28.391 15479 15545 E unknown:DisabledDevSupportManager: Bl@1:249874
01-30 21:00:28.391 15479 15545 E unknown:DisabledDevSupportManager: anonymous@1:259256
01-30 21:00:28.391 15479 15545 E unknown:DisabledDevSupportManager: unmountApplicationComponentAtRootTag@1:520609
01-30 21:00:28.391 15479 15545 E unknown:DisabledDevSupportManager: value@1:151999
01-30 21:00:28.391 15479 15545 E unknown:DisabledDevSupportManager: anonymous@1:150501
01-30 21:00:28.391 15479 15545 E unknown:DisabledDevSupportManager: value@1:151471
01-30 21:00:28.391 15479 15545 E unknown:DisabledDevSupportManager: value@1:150459
01-30 21:00:28.391 15479 15545 E unknown:DisabledDevSupportManager: 
01-30 21:00:28.391 15479 15545 E unknown:DisabledDevSupportManager: 	at com.facebook.react.modules.core.ExceptionsManagerModule.reportException(ExceptionsManagerModule.java:83)
01-30 21:00:28.391 15479 15545 E unknown:DisabledDevSupportManager: 	at java.lang.reflect.Method.invoke(Native Method)
01-30 21:00:28.391 15479 15545 E unknown:DisabledDevSupportManager: 	at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:372)
01-30 21:00:28.391 15479 15545 E unknown:DisabledDevSupportManager: 	at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:151)
01-30 21:00:28.391 15479 15545 E unknown:DisabledDevSupportManager: 	at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
01-30 21:00:28.391 15479 15545 E unknown:DisabledDevSupportManager: 	at android.os.Handler.handleCallback(Handler.java:883)
01-30 21:00:28.391 15479 15545 E unknown:DisabledDevSupportManager: 	at android.os.Handler.dispatchMessage(Handler.java:100)
01-30 21:00:28.391 15479 15545 E unknown:DisabledDevSupportManager: 	at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:27)
01-30 21:00:28.391 15479 15545 E unknown:DisabledDevSupportManager: 	at android.os.Looper.loop(Looper.java:241)
01-30 21:00:28.391 15479 15545 E unknown:DisabledDevSupportManager: 	at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:226)
01-30 21:00:28.391 15479 15545 E unknown:DisabledDevSupportManager: 	at java.lang.Thread.run(Thread.java:919)
01-30 21:00:28.392 15479 15545 E AndroidRuntime: FATAL EXCEPTION: mqt_native_modules
01-30 21:00:28.392 15479 15545 E AndroidRuntime: Process: me.rainbow, PID: 15479
01-30 21:00:28.392 15479 15545 E AndroidRuntime: com.facebook.react.common.JavascriptException: TypeError: Object is not a function
01-30 21:00:28.392 15479 15545 E AndroidRuntime: 
01-30 21:00:28.392 15479 15545 E AndroidRuntime: This error is located at:
01-30 21:00:28.392 15479 15545 E AndroidRuntime:     in Unknown
01-30 21:00:28.392 15479 15545 E AndroidRuntime:     in w
01-30 21:00:28.392 15479 15545 E AndroidRuntime:     in A
01-30 21:00:28.392 15479 15545 E AndroidRuntime:     in A
01-30 21:00:28.392 15479 15545 E AndroidRuntime:     in s
01-30 21:00:28.392 15479 15545 E AndroidRuntime:     in A
01-30 21:00:28.392 15479 15545 E AndroidRuntime:     in Unknown
01-30 21:00:28.392 15479 15545 E AndroidRuntime:     in P
01-30 21:00:28.392 15479 15545 E AndroidRuntime:     in RCTView
01-30 21:00:28.392 15479 15545 E AndroidRuntime:     in View
01-30 21:00:28.392 15479 15545 E AndroidRuntime:     in RCTView
01-30 21:00:28.392 15479 15545 E AndroidRuntime:     in View
01-30 21:00:28.392 15479 15545 E AndroidRuntime:     in p, js engine: hermes, stack:
01-30 21:00:28.392 15479 15545 E AndroidRuntime: anonymous@1:233827
01-30 21:00:28.392 15479 15545 E AndroidRuntime: anonymous@1:306955
01-30 21:00:28.392 15479 15545 E AndroidRuntime: Lt@1:211869
01-30 21:00:28.392 15479 15545 E AndroidRuntime: ei@1:233783
01-30 21:00:28.392 15479 15545 E AndroidRuntime: ai@1:235759
01-30 21:00:28.392 15479 15545 E AndroidRuntime: gl@1:245028
01-30 21:00:28.392 15479 15545 E AndroidRuntime: anonymous@1:306955
01-30 21:00:28.392 15479 15545 E AndroidRuntime: Lt@1:211869
01-30 21:00:28.392 15479 15545 E AndroidRuntime: ml@1:244296
01-30 21:00:28.392 15479 15545 E AndroidRuntime: rl@1:241223
01-30 21:00:28.392 15479 15545 E AndroidRuntime: anonymous@1:212396
01-30 21:00:28.392 15479 15545 E AndroidRuntime: anonymous@1:306955
01-30 21:00:28.392 15479 15545 E AndroidRuntime: Lt@1:211869
01-30 21:00:28.392 15479 15545 E AndroidRuntime: Wt@1:212214
01-30 21:00:28.392 15479 15545 E AndroidRuntime: jt@1:212108
01-30 21:00:28.392 15479 15545 E AndroidRuntime: Ji@1:238440
01-30 21:00:28.392 15479 15545 E AndroidRuntime: Ql@1:249568
01-30 21:00:28.392 15479 15545 E AndroidRuntime: Bl@1:249874
01-30 21:00:28.392 15479 15545 E AndroidRuntime: anonymous@1:259256
01-30 21:00:28.392 15479 15545 E AndroidRuntime: unmountApplicationComponentAtRootTag@1:520609
01-30 21:00:28.392 15479 15545 E AndroidRuntime: value@1:151999
01-30 21:00:28.392 15479 15545 E AndroidRuntime: anonymous@1:150501
01-30 21:00:28.392 15479 15545 E AndroidRuntime: value@1:151471
01-30 21:00:28.392 15479 15545 E AndroidRuntime: value@1:150459
01-30 21:00:28.392 15479 15545 E AndroidRuntime: 
01-30 21:00:28.392 15479 15545 E AndroidRuntime: 	at com.facebook.react.modules.core.ExceptionsManagerModule.reportException(ExceptionsManagerModule.java:83)
01-30 21:00:28.392 15479 15545 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
01-30 21:00:28.392 15479 15545 E AndroidRuntime: 	at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:372)
01-30 21:00:28.392 15479 15545 E AndroidRuntime: 	at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:151)
01-30 21:00:28.392 15479 15545 E AndroidRuntime: 	at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
01-30 21:00:28.392 15479 15545 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:883)
01-30 21:00:28.392 15479 15545 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:100)
01-30 21:00:28.392 15479 15545 E AndroidRuntime: 	at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:27)
01-30 21:00:28.392 15479 15545 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:241)
01-30 21:00:28.392 15479 15545 E AndroidRuntime: 	at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:226)
01-30 21:00:28.392 15479 15545 E AndroidRuntime: 	at java.lang.Thread.run(Thread.java:919)
01-30 21:00:28.402  4110  4110 D MOTO_ERD9610_PowerHAL: POWER_HINT_LAUNCH 0

```

**Comment by skylarbarrera** [comment]
Hey @ligi ,

These logs are not very helpful for us to repro and try to fix on our end! 
Please try to attach some context or more info if possible!

**Comment by ligi** [comment]
For this one I have no context - just happened. Cannot repro but got this crash

**Comment by skylarbarrera** [comment]
@ligi Thanks! Will keep an eye out, feel free to reopen if you run into the same issue again!
