### ISSUE TITLE
Help me

### ISSUE THREAD

**Issue by shieldwallets** [rainbow-me/rainbow#2383]
Error: command failed
    at ChildProcess.<anonymous> (/Users/leo/Desktop/code/rainbow-1.5.23/node_modules/@npmcli/promise-spawn/index.js:64:27)
    at ChildProcess.emit (events.js:315:20)
    at maybeClose (internal/child_process.js:1048:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:288:5) {
  cmd: 'sh',
  args: [ '-c', './scripts/postinstall.sh' ],
  code: 1,
  signal: null,
  stdout: '',
  stderr: '',
  event: 'postinstall',
  script: './scripts/postinstall.sh',
  pkgid: 'Rainbow@1.5.24-1',
  path: '/Users/leo/Desktop/code/rainbow-1.5.23'
}
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Comment by okanpehlivan** [comment]
GOOGLE_SERVICE_API_KEY=AIz***

Add this variable => **'GOOGLE_SERVICE_API_KEY'** to your .env file
If you added firebase files. You can find this variable in ios/GoogleService-Info.plist
