### ISSUE TITLE
@uniswap/token-lists not accessible from rainbow-token-list

### ISSUE THREAD

**Issue by goretushar** [rainbow-me/rainbow#2480]
**I have setup my .env file, .sentryclirc file, also I have updated sentry.property file in ios folder.**

I am trying to setup yarn with following command.
**yarn setup sh ./scripts/postinstall.sh**

I am getting following error, Please Help

**Error: @uniswap/token-lists not accessible from rainbow-token-list**
    at /Users/testuser/Desktop/New_Rainbow_Wallet/rainbow/node_modules/@lavamoat/allow-scripts/src/yarnLogicalTree.js:118:15
    at Array.forEach (<anonymous>)
    at addChild (/Users/testuser/Desktop/New_Rainbow_Wallet/rainbow/node_modules/@lavamoat/allow-scripts/src/yarnLogicalTree.js:112:29)
    at /Users/testuser/Desktop/New_Rainbow_Wallet/rainbow/node_modules/@lavamoat/allow-scripts/src/yarnLogicalTree.js:94:7
    at Array.forEach (<anonymous>)
    at Object.loadTree (/Users/testuser/Desktop/New_Rainbow_Wallet/rainbow/node_modules/@lavamoat/allow-scripts/src/yarnLogicalTree.js:81:6)
    at loadTree (/Users/testuser/Desktop/New_Rainbow_Wallet/rainbow/node_modules/@lavamoat/allow-scripts/src/index.js:353:28)
    at async loadAllPackageConfigurations (/Users/testuser/Desktop/New_Rainbow_Wallet/rainbow/node_modules/@lavamoat/allow-scripts/src/index.js:448:33)
    at async runAllowedPackages (/Users/testuser/Desktop/New_Rainbow_Wallet/rainbow/node_modules/@lavamoat/allow-scripts/src/index.js:33:7)
    at async start (/Users/testuser/Desktop/New_Rainbow_Wallet/rainbow/node_modules/@lavamoat/allow-scripts/src/cli.js:21:7)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Comment by shawnmitchell** [comment]
I'm stuck at the same point. I suspect it's a `.env` problem but that's just a guess.
